// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: src/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateKernelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int32 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 1 for success, 0 for failure.
}

func (x *MigrateKernelResponse) Reset() {
	*x = MigrateKernelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateKernelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateKernelResponse) ProtoMessage() {}

func (x *MigrateKernelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateKernelResponse.ProtoReflect.Descriptor instead.
func (*MigrateKernelResponse) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *MigrateKernelResponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// Used as an argument to RPC calls to refer to a specific kernel.
type JupyterKernelArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelId  string `protobuf:"bytes,1,opt,name=kernelId,proto3" json:"kernelId,omitempty"`
	ReplicaId int32  `protobuf:"varint,2,opt,name=replicaId,proto3" json:"replicaId,omitempty"`
}

func (x *JupyterKernelArg) Reset() {
	*x = JupyterKernelArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JupyterKernelArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterKernelArg) ProtoMessage() {}

func (x *JupyterKernelArg) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterKernelArg.ProtoReflect.Descriptor instead.
func (*JupyterKernelArg) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *JupyterKernelArg) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *JupyterKernelArg) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

type DistributedJupyterKernel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelId            string                  `protobuf:"bytes,1,opt,name=kernelId,proto3" json:"kernelId,omitempty"`
	NumReplicas         int32                   `protobuf:"varint,2,opt,name=numReplicas,proto3" json:"numReplicas,omitempty"`
	Status              string                  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AggregateBusyStatus string                  `protobuf:"bytes,4,opt,name=aggregateBusyStatus,proto3" json:"aggregateBusyStatus,omitempty"`
	Replicas            []*JupyterKernelReplica `protobuf:"bytes,5,rep,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *DistributedJupyterKernel) Reset() {
	*x = DistributedJupyterKernel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributedJupyterKernel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedJupyterKernel) ProtoMessage() {}

func (x *DistributedJupyterKernel) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedJupyterKernel.ProtoReflect.Descriptor instead.
func (*DistributedJupyterKernel) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DistributedJupyterKernel) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *DistributedJupyterKernel) GetNumReplicas() int32 {
	if x != nil {
		return x.NumReplicas
	}
	return 0
}

func (x *DistributedJupyterKernel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DistributedJupyterKernel) GetAggregateBusyStatus() string {
	if x != nil {
		return x.AggregateBusyStatus
	}
	return ""
}

func (x *DistributedJupyterKernel) GetReplicas() []*JupyterKernelReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

// Received as a response from RPC calls; contains additional info.
type JupyterKernelReplica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelId  string `protobuf:"bytes,1,opt,name=kernelId,proto3" json:"kernelId,omitempty"`
	ReplicaId int32  `protobuf:"varint,2,opt,name=replicaId,proto3" json:"replicaId,omitempty"`
	PodId     string `protobuf:"bytes,3,opt,name=podId,proto3" json:"podId,omitempty"`
	NodeId    string `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *JupyterKernelReplica) Reset() {
	*x = JupyterKernelReplica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JupyterKernelReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JupyterKernelReplica) ProtoMessage() {}

func (x *JupyterKernelReplica) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JupyterKernelReplica.ProtoReflect.Descriptor instead.
func (*JupyterKernelReplica) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *JupyterKernelReplica) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *JupyterKernelReplica) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *JupyterKernelReplica) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *JupyterKernelReplica) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListKernelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumKernels int32                       `protobuf:"varint,1,opt,name=numKernels,proto3" json:"numKernels,omitempty"`
	Kernels    []*DistributedJupyterKernel `protobuf:"bytes,2,rep,name=kernels,proto3" json:"kernels,omitempty"`
}

func (x *ListKernelsResponse) Reset() {
	*x = ListKernelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKernelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKernelsResponse) ProtoMessage() {}

func (x *ListKernelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKernelsResponse.ProtoReflect.Descriptor instead.
func (*ListKernelsResponse) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *ListKernelsResponse) GetNumKernels() int32 {
	if x != nil {
		return x.NumKernels
	}
	return 0
}

func (x *ListKernelsResponse) GetKernels() []*DistributedJupyterKernel {
	if x != nil {
		return x.Kernels
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_driver_driver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_src_driver_driver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_src_driver_driver_proto_rawDescGZIP(), []int{5}
}

var File_src_driver_driver_proto protoreflect.FileDescriptor

var file_src_driver_driver_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x22, 0x31, 0x0a, 0x15, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x4c, 0x0a, 0x10, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x4b,
	0x65, 0x72, 0x6e, 0x65, 0x6c, 0x41, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x49, 0x64, 0x22, 0xdc, 0x01, 0x0a, 0x18, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x64, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6e,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x42, 0x75, 0x73, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x2e, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x73, 0x22, 0x7e, 0x0a, 0x14, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x22, 0x71, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4b,
	0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75,
	0x6d, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x3a, 0x0a, 0x07, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x4a, 0x75,
	0x70, 0x79, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x73, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x32, 0xab, 0x01, 0x0a,
	0x1a, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x65,
	0x62, 0x6f, 0x6f, 0x6b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x0c, 0x2e, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x1b, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x14, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12,
	0x18, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x75, 0x70, 0x79, 0x74, 0x65, 0x72,
	0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x41, 0x72, 0x67, 0x1a, 0x1d, 0x2e, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x7f, 0x0a, 0x36, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x6a, 0x79,
	0x72, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x6e, 0x6f,
	0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x42, 0x0b, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x68, 0x61, 0x6e, 0x67, 0x6a, 0x79, 0x72, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x64, 0x2d, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_src_driver_driver_proto_rawDescOnce sync.Once
	file_src_driver_driver_proto_rawDescData = file_src_driver_driver_proto_rawDesc
)

func file_src_driver_driver_proto_rawDescGZIP() []byte {
	file_src_driver_driver_proto_rawDescOnce.Do(func() {
		file_src_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_driver_driver_proto_rawDescData)
	})
	return file_src_driver_driver_proto_rawDescData
}

var file_src_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_driver_driver_proto_goTypes = []interface{}{
	(*MigrateKernelResponse)(nil),    // 0: driver.MigrateKernelResponse
	(*JupyterKernelArg)(nil),         // 1: driver.JupyterKernelArg
	(*DistributedJupyterKernel)(nil), // 2: driver.DistributedJupyterKernel
	(*JupyterKernelReplica)(nil),     // 3: driver.JupyterKernelReplica
	(*ListKernelsResponse)(nil),      // 4: driver.ListKernelsResponse
	(*Void)(nil),                     // 5: driver.Void
}
var file_src_driver_driver_proto_depIdxs = []int32{
	3, // 0: driver.DistributedJupyterKernel.replicas:type_name -> driver.JupyterKernelReplica
	2, // 1: driver.ListKernelsResponse.kernels:type_name -> driver.DistributedJupyterKernel
	5, // 2: driver.DistributedNotebookCluster.ListKernels:input_type -> driver.Void
	1, // 3: driver.DistributedNotebookCluster.MigrateKernelReplica:input_type -> driver.JupyterKernelArg
	4, // 4: driver.DistributedNotebookCluster.ListKernels:output_type -> driver.ListKernelsResponse
	0, // 5: driver.DistributedNotebookCluster.MigrateKernelReplica:output_type -> driver.MigrateKernelResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_driver_driver_proto_init() }
func file_src_driver_driver_proto_init() {
	if File_src_driver_driver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_driver_driver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateKernelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_driver_driver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JupyterKernelArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_driver_driver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributedJupyterKernel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_driver_driver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JupyterKernelReplica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_driver_driver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKernelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_driver_driver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_driver_driver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_driver_driver_proto_goTypes,
		DependencyIndexes: file_src_driver_driver_proto_depIdxs,
		MessageInfos:      file_src_driver_driver_proto_msgTypes,
	}.Build()
	File_src_driver_driver_proto = out.File
	file_src_driver_driver_proto_rawDesc = nil
	file_src_driver_driver_proto_goTypes = nil
	file_src_driver_driver_proto_depIdxs = nil
}
